export const sliderData = [
  {
    image: "/images/image-1.jpg",
    heading: "Welcome",
    desc: "Welcome to my portfolio page",
    button: "Get started",
    btnClassName: "-start",
    cntClassName: "-welcome",
    link: "/",
    insideLink: "#--section1",
  },
  {
    image: "/images/image-2.jpg",
    heading: "My Resume",
    desc: "lorem ipsum dolor",
    button: "Resume",
    btnClassName: "-resume",
    cntClassName: "-my-resume",
    link: "/Resume",
  },
  {
    image: "/images/image-3.jpg",
    heading: "My projects",
    desc: "lorem ipsum dolor",
    button: "Projects",
    btnClassName: "-projects",
    cntClassName: "-my-projects",
    link: "/Projects",
  },
  {
    image: "/images/image-4.jpg",
    heading: "contact",
    desc: "lorem ipsum dolor",
    button: "Contact",
    btnClassName: "-contact",
    cntClassName: "-my-contacts",
    link: "/Contact",
  },
];
export default sliderData;
