export const projectData = [
  {
    key: 1,
    image: "/images/bankist-website.PNG",
    heading: "Bankist",
    desc: "Landing page for modern minimalist banking - all rights have been reserved by the instructor Jonas Schmedtmann",
    link: "https://bankistanna.netlify.app",
    className: "bankist",
    linkText: "Visit Bankist",
    gitLink: "https://github.com/Anna-Koberidze/bankist-website",
  },
  {
    key: 2,
    image: "/images/bankist-app.jpg",
    heading: "Bankist-App",
    desc: " application for modern minimalist banking - all rights have been reserved by the instructor Jonas Schmedtmann",
    link: "https://bankist-app-anna.netlify.app",
    className: "bankist-app",
    linkText: "Visit Bankist-App",
    gitLink: "https://github.com/Anna-Koberidze/bankist-app",
  },
  {
    key: 3,
    image: "/images/mapty.jpg",
    heading: "Mapty",
    desc: "application for recording workouts on a map - all rights have been reserved by the instructor Jonas Schmedtmann",
    link: "https://mapty-anna.netlify.app",
    className: "mapty",
    linkText: "Visit Mapty",
    gitLink: "https://github.com/Anna-Koberidze/mapty",
  },
  {
    key: 4,
    image: "/images/hundredDays.jpg",
    heading: "100 days of code",
    desc: "100 days of code calendar for checking off progress",
    link: "https://100daysofcodecalendar.netlify.app",
    className: "days-of-code",
    linkText: "Visit 100 days of code",
    gitLink: "https://github.com/Anna-Koberidze/100-days-of-code-calendar",
  },
];
export default projectData;
